// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcyfXdUF2x1xNLBr8rtFTEHJ-pIu_oVU',
    appId: '1:1083102738052:web:abb0db417d6cfcd9e534d1',
    messagingSenderId: '1083102738052',
    projectId: 'family-9e043',
    authDomain: 'family-9e043.firebaseapp.com',
    storageBucket: 'family-9e043.firebasestorage.app',
    measurementId: 'G-3NG04BX8WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKskjdYO2r8qH5AMYsjSdVx48JvBKmps',
    appId: '1:1083102738052:android:08a78aaa0ae7abfae534d1',
    messagingSenderId: '1083102738052',
    projectId: 'family-9e043',
    storageBucket: 'family-9e043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyKtB6rh9tHPYje6zV0PLogPyp14oGdo',
    appId: '1:1083102738052:ios:2a2979dd27451bf8e534d1',
    messagingSenderId: '1083102738052',
    projectId: 'family-9e043',
    storageBucket: 'family-9e043.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyKtB6rh9tHPYje6zV0PLogPyp14oGdo',
    appId: '1:1083102738052:ios:2a2979dd27451bf8e534d1',
    messagingSenderId: '1083102738052',
    projectId: 'family-9e043',
    storageBucket: 'family-9e043.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdcyfXdUF2x1xNLBr8rtFTEHJ-pIu_oVU',
    appId: '1:1083102738052:web:c3ca6dc6c3d93805e534d1',
    messagingSenderId: '1083102738052',
    projectId: 'family-9e043',
    authDomain: 'family-9e043.firebaseapp.com',
    storageBucket: 'family-9e043.firebasestorage.app',
    measurementId: 'G-J9CES5RL6B',
  );
}
